### ISSUE TITLE
Too many layers of irony

### ISSUE THREAD

**Issue by brettinternet** [tylerjl/tylerjl#1]
Tyler,

I can only fathom one layer of irony, however this has surpassed multiple abstractions of cultural irony it's now incomprehensible to me.

Is this markdown? Is this 1990's HTML? Is this just fantasy?

**Comment by tylerjl** [comment]
> Caught on server side
> Escape proprietary
>
> Open your vi
> Look up your keybinds and see
> I'm just a poor dev, I need no IDE
> Because it's easy in `NORMAL` mode
> Plugins high, memory low
> Any editor wars never really matter to me... to me

![image](https://user-images.githubusercontent.com/1733846/93840849-0b466480-fc4f-11ea-84a6-9fd8b5388f9f.png)
